import { useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { Plus } from "lucide-react";
import { Eyebrow, Reveal, Section } from "./Primitives";

type Faq = { q: string; a: React.ReactNode };

const sl = "space-y-3 text-[0.98rem] leading-relaxed text-slate";
const li = "flex items-start gap-2 text-[0.98rem] leading-relaxed text-slate";

const faqs: Faq[] = [
  {
    q: "Where does the part and fitment data come from?",
    a: (
      <p className="text-[0.98rem] leading-relaxed text-slate">
        PartLister uses trusted TecDoc product and vehicle data to generate listings with OE references, interchangeable numbers, compatibility, engine codes and technical specifications. We don't invent product data with AI.
      </p>
    ),
  },
  {
    q: "What can I enter to generate a listing?",
    a: (
      <div className={sl}>
        <p>You can generate a listing using:</p>
        <ul className="space-y-1 pl-1">
          {["OE Number", "OEM Number", "TecDoc Article Number"].map((s) => (
            <li key={s} className={li}><span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />{s}</li>
          ))}
        </ul>
        <p>Simply paste your reference number and PartLister builds the listing automatically.</p>
      </div>
    ),
  },
  {
    q: "What does PartLister generate?",
    a: (
      <div className={sl}>
        <p>Every listing can include:</p>
        <ul className="space-y-1 pl-1">
          {[
            "SEO-optimised title",
            "Product description",
            "Item specifics",
            "Vehicle compatibility",
            "Engine codes",
            "OE references",
            "Interchangeable numbers",
            "Market pricing",
            "CSV export",
          ].map((s) => (
            <li key={s} className={li}>
              <span className="mt-0.5 shrink-0 text-successg font-bold">✓</span>
              {s}
            </li>
          ))}
        </ul>
      </div>
    ),
  },
  {
    q: "Is the compatibility data accurate?",
    a: (
      <div className={sl}>
        <p>Compatibility is generated directly from TecDoc vehicle application data.</p>
        <p>We always recommend verifying compatibility before publishing, but PartLister removes the need to manually research hundreds of applications yourself.</p>
      </div>
    ),
  },
  {
    q: "How does the free trial work?",
    a: (
      <ul className="space-y-1.5 pl-1">
        {[
          "Every new account includes 10 free listings.",
          "No credit card required.",
          "You can explore every core feature before choosing a subscription.",
        ].map((s) => (
          <li key={s} className={li}><span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />{s}</li>
        ))}
      </ul>
    ),
  },
  {
    q: "Can I export my listings?",
    a: (
      <div className={sl}>
        <p>Yes. You can instantly:</p>
        <ul className="space-y-1 pl-1">
          {[
            "Copy HTML",
            "Export to CSV",
            "Save listings for later",
            "Use your preferred marketplace workflow",
          ].map((s) => (
            <li key={s} className={li}><span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />{s}</li>
          ))}
        </ul>
      </div>
    ),
  },
  {
    q: "Does PartLister calculate eBay fees and profit?",
    a: (
      <div className={sl}>
        <p>Yes. Our Smart Pricing tool calculates:</p>
        <ul className="space-y-1 pl-1">
          {["eBay fees", "VAT", "Shipping", "Packaging", "Advertising costs", "Profit", "Margin", "Markup"].map((s) => (
            <li key={s} className={li}><span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />{s}</li>
          ))}
        </ul>
        <p>Helping you price every listing confidently.</p>
      </div>
    ),
  },
  {
    q: "Is AI writing my listings?",
    a: (
      <div className={sl}>
        <p>AI helps optimise titles and descriptions.</p>
        <p>Your product specifications, compatibility and OE references come from trusted automotive data sources rather than being generated by AI.</p>
        <p>This gives you the speed of AI with the reliability of verified catalogue data.</p>
      </div>
    ),
  },
  {
    q: "Who is PartLister for?",
    a: (
      <div className={sl}>
        <p>PartLister is built for:</p>
        <ul className="space-y-1 pl-1">
          {[
            "eBay sellers",
            "Motor factors",
            "Automotive retailers",
            "Engine rebuilders",
            "Parts distributors",
            "Salvage yards",
            "Commercial vehicle specialists",
          ].map((s) => (
            <li key={s} className={li}><span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />{s}</li>
          ))}
        </ul>
        <p>Anyone creating automotive parts listings at scale.</p>
      </div>
    ),
  },
  {
    q: "Why use PartLister instead of copying from TecDoc?",
    a: (
      <div className={sl}>
        <p>Instead of manually copying information between TecDoc, eBay and spreadsheets, PartLister generates a complete listing in seconds.</p>
        <p>That means:</p>
        <ul className="space-y-1 pl-1">
          {["Less manual work", "Fewer mistakes", "Better SEO", "Consistent listings", "More time selling"].map((s) => (
            <li key={s} className={li}><span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />{s}</li>
          ))}
        </ul>
      </div>
    ),
  },
];

function Item({ q, a, i }: { q: string; a: React.ReactNode; i: number }) {
  const [open, setOpen] = useState(false);
  return (
    <Reveal delay={i * 0.04}>
      <div className={`overflow-hidden rounded-2xl border bg-white transition-colors ${open ? "border-primary/30 shadow-soft" : "border-hair"}`}>
        <button
          onClick={() => setOpen((v) => !v)}
          className="flex w-full items-center justify-between gap-4 px-6 py-5 text-left"
        >
          <span className="text-[1.02rem] font-semibold text-navy">{q}</span>
          <span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full transition-all duration-300 ${open ? "rotate-45 bg-primary text-white" : "bg-wash text-primary"}`}>
            <Plus className="h-4 w-4" />
          </span>
        </button>
        <AnimatePresence initial={false}>
          {open && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: "auto", opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
            >
              <div className="px-6 pb-6">{a}</div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </Reveal>
  );
}

export default function FAQ() {
  return (
    <Section id="faq" className="py-24 sm:py-28">
      <Reveal className="mx-auto max-w-2xl text-center">
        <Eyebrow>FAQ</Eyebrow>
        <h2 className="font-display text-[clamp(2rem,4vw,3rem)] font-extrabold tracking-tightest text-navy text-balance">
          Everything you need to know
        </h2>
      </Reveal>

      <div className="mx-auto mt-12 flex max-w-2xl flex-col gap-3">
        {faqs.map((f, i) => (
          <Item key={f.q} q={f.q} a={f.a} i={i} />
        ))}
      </div>
    </Section>
  );
}
